openapi: 3.0.1
info:
  title: GMail Skill
  description: A VertexGraph skill to access user's GMail account
  version: 1.0.0
servers:
  - url: $skillhost
paths:
  $skillapproot/messages/query:
    post:
      operationId: QueryEmails
      summary: Query the email messages in the user's mailbox
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryEmailsResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryEmailsRequest"
        required: true
  $skillapproot/threads/query:
    post:
      operationId: QueryEmailThreads
      summary: Query the threads in the user's mailbox
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryEmailThreadsResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryEmailThreadsRequest"
        required: true
components:
  schemas:
    GMailMessage:
      title: GMailMessage
      required:
        - id
        - subject
      type: object
      properties:
        id:
          title: Id
          type: string
        subject:
          title: Subject
          type: string
        body:
          title: Body
          type: string
    GMailThread:
      title: GMailThread
      required:
        - id
        - subject
      type: object
      properties:
        id:
          title: Id
          type: string
        subject:
          title: Subject
          type: string
    QueryEmailsResponse:
      type: object
      properties:
        emailMessages:
          type: array
          items:
            $ref: "#/components/schemas/GMailMessage"
          description: The list of GMail messages.
    QueryEmailThreadsResponse:
      type: object
      properties:
        emailThreads:
          type: array
          items:
            $ref: "#/components/schemas/GMailThread"
          description: The list of GMail email threads.
    QueryEmailsRequest:
      title: QueryEmailsRequest
      required:
        - query
      type: object
      properties:
        query:
          title: Query
          type: string
          description: filter to query the emails
        begin_time:
          title: Begin Time
          type: string         
          description: Messages sent after this time will be returned.
        end_time:
          title: End Time
          type: string         
          description: Messages sent before this time will be returned.
    QueryEmailThreadsRequest:
      title: QueryEmailThreadsRequest
      required:
        - query
      type: object
      properties:
        query:
          title: Query
          type: string
          description: filter to query the email threads
        begin_time:
          title: Begin Time
          type: string         
          description: Email threads sent after this time will be returned.
        end_time:
          title: End Time
          type: string         
          description: Email threads sent before this time will be returned.